In [1]:
import pandas as pd

filename ='Users\Owner\PycharmProjects\CSC3130\WebProject_KyleMcLean\Briefs\2017-02-18CraigslistBriefs.json'
#filename = 'C:\Users\username\pathToFile\fileName.json'
#filename = 'fileName.json'
data = pd.read_json('2017-02-18CraigslistBriefs.json')

ValueError: No ':' found when decoding object value

In [ ]:
data

In [2]:
import pandas as pd

filename ='Users\Owner\PycharmProjects\CSC3130\WebProject_KyleMcLean\Briefs\2017-02-18CraigslistBriefs.json'
#filename = 'C:\Users\username\pathToFile\fileName.json'
#filename = 'fileName.json'
data = pd.read_json('2017-02-18CraigslistBriefs.json')

ValueError: No ':' found when decoding object value

In [3]:
import pandas as pd

filename ='Users\Owner\PycharmProjects\CSC3130\WebProject_KyleMcLean\Briefs\2017-02-18CraigslistBriefs.json'
#filename = 'C:\Users\username\pathToFile\fileName.json'
#filename = 'fileName.json'
data = pd.read_json('2017-02-18.RentBriefs.json')

In [4]:
data

                location           phone  price    size
0   (Downtown Nashville)  (844) 538-9754  $1399   1 Bed
1   (Historic Edgefield)  (844) 793-7781  $2000  2 Beds
2   (Cumberland Gardens)  (844) 887-7125   $850  2 Beds
3             (East End)  (877) 432-6013  $1500  2 Beds
4        (West End Park)  (844) 711-6208  $1195   1 Bed
5          (Green Hills)  (888) 923-3149  $1100   1 Bed
6    (Glencliff Estates)  (888) 630-1984  $1650  3 Beds
7                   None  (844) 509-3762  $2395  4 Beds
8      (Talbot's Corner)  (844) 320-2437  $1645  3 Beds
9                   None  (844) 783-5359  $1800  3 Beds
10              (Radnor)  (844) 610-7947  $1250  3 Beds
11          (River Glen)  (844) 865-5196  $1450  3 Beds
12                  None  (844) 783-5368  $1049  2 Beds
13                  None  (855) 233-2803  $1575  3 Beds
14   (Bellshire Terrace)  (844) 865-5197  $1395  3 Beds
15    (Whispering Hills)  (844) 585-1387  $2000  3 Beds
16            (McMurray)  (844) 792-5991  $1150  2 Beds
17                  None  (844) 322-8969  $1050  2 Beds
18                  None  (855) 233-2803  $1895  3 Beds
19                  None  (855) 233-2803  $1695  3 Beds

In [5]:
data2 = pd.read_json('2017-02-18.CraigslsitBriefs.json')

In [6]:
data2

                                             location       price        size
0     (159 Mansker Park Dr, Hendersonville, TN 37075)       $1870  Not listed
1                                    (900 19th Ave S)       $1375  Not listed
2                                         (Nashville)        $900  Not listed
3                                           (Oakland)        $950  Not listed
4                                       (Spring Hill)       $1800         3br
5                                (Downtown Nashville)       $2000  Not listed
6                                      (Murfreesboro)       $1030  Not listed
7                                         (Nashville)        $905  Not listed
8                      (108 Thompson Ln Nashville TN)        $900  Not listed
9                                         (Grassland)       $3000  Not listed
10                                    (Nashville, TN)       $1490  Not listed
11                (Nashville - Vanderbilt University)       $1525  Not listed
12                                 (near Rose Pepper)       $1300         1br
13                                 (2505 Preston way)       $1649  Not listed
14                                   (Sylvan Heights)       $1475  Not listed
15                                        (Nashville)       $1169  Not listed
16                                    (nashville\tTN)        $780         3br
17                                        (Nashville)       $1137  Not listed
18                                         Not listed        $800  Not listed
19       (1000 Amberwood Circle, Nashville, TN 37221)        $934  Not listed
20                                        (Nashville)       $1590  Not listed
21                                       (, ,  37075)        $860  Not listed
22             (865 Bellevue Rd, Nashville, TN 37221)       $1197  Not listed
23                                        (Nashville)       $1180         2br
24                                    (Nashville, TN)       $1152  Not listed
25                                         Not listed        $832  Not listed
26          (Cool Springs/Franklin/Williamson County)       $1099  Not listed
27                   (Elliston, West End, Vanderbilt)       $1299         1br
28                      (Riverside Village/Inglewood)       $1800  Not listed
29                         (Inglewood/East Nashville)       $2400         4br
..                                                ...         ...         ...
70               (1650 Cason, Murfreesboro, TN 37128)       $1160  Not listed
71                     (3525 West End Ave, Nashville)       $1650  Not listed
72                                    (nashville, tn)        $831  Not listed
73                                         Not listed        $900         2br
74                                         Not listed       $1100         2br
75                                         Not listed       $1175         3br
76                                         Not listed       $1016  Not listed
77                                         Not listed        $675         3br
78                                         Not listed        $795         3br
79                                         Not listed        $975         3br
80                                         Not listed        $775         2br
81                                         (Franklin)       $1306  Not listed
82                                        (Nashville)       $1249  Not listed
83                                   (Goodlettsville)       $1200  Not listed
84   (5901 Old Hickory Boulevard, Hermitage, TN 37...       $1010         1br
85                                         (Downtown)       $1633  Not listed
86                                    (Nashville, TN)       $1205  Not listed
87               (1500 Brentridge, Antioch, TN 37013)       $1175  Not listed
88                                         Not listed        $978  Not listed
89                               (Downtown Nashville)       $1249  Not listed
90                                     (Franklin, TN)       $1815  Not listed
91                                        (Nashville)        $430         5br
92                   (Nashville,West End, Vanderbilt)  Not listed  Not listed
93                                         Not listed       $1149         1br
94            (1043 Daniel Ln, Spring Hill, TN 37174)       $1995  Not listed
95                                         Not listed        $829  Not listed
96                                     (Nashville TN)       $1068  Not listed
97                                         Not listed        $800  Not listed
98                                     (Murfreesboro)        $965  Not listed
99                                     (Murfreesboro)        $965  Not listed

[100 rows x 3 columns]

In [7]:
data3 = pd.read_json('2017-02-18CraigslistBriefs.json')

ValueError: No ':' found when decoding object value

In [8]:
data3 = pd.read_json('2017-02-18CraigslistBriefs.json')

In [9]:
data3

,location,phone,price,size
0,(Nashville),NaN,$1525,NaN
1,(Hendersonville),NaN,$859,NaN
2,"(1650 Cason, Murfreesboro, TN 37128)",NaN,$1160,NaN
3,"(3525 West End Ave, Nashville)",NaN,$1650,NaN
4,"(nashville, tn)",NaN,$831,NaN
5,(Franklin),NaN,$1306,NaN
6,(Nashville),NaN,$1249,NaN
7,(Goodlettsville),NaN,$1200,NaN
8,"(5901 Old Hickory Boulevard, Hermitage, TN 37...",NaN,$1010,NaN
9,(Downtown),NaN,$1633,NaN
10,"(Nashville, TN)",NaN,$1205,NaN
11,"(1500 Brentridge, Antioch, TN 37013)",NaN,$1175,NaN
12,(Downtown Nashville),NaN,$1249,NaN
13,"(Franklin, TN)",NaN,$1815,NaN
14,(Nashville),NaN,$430,NaN
15,"(1043 Daniel Ln, Spring Hill, TN 37174)",NaN,$1995,NaN
16,(Nashville TN),NaN,$1068,NaN
17,(Murfreesboro),NaN,$965,NaN
18,(Murfreesboro),NaN,$965,NaN
19,(Downtown Nashville),NaN,$1249,NaN
20,(Franklin),NaN,$1125,NaN
21,(Murfreesboro),NaN,$965,NaN
22,(Franklin),NaN,$1306,NaN
23,(nashville\tTN),NaN,$715,NaN
24,(West End/ Vanderbilt/ Medical Center),NaN,$1153,NaN
25,(Vandy/Green Hills area),NaN,$1550,NaN
26,"(1000 Amberwood Circle, Nashville, TN 37221)",NaN,$1437,NaN
27,(Nashville),NaN,$1249,NaN
28,(Nashville),NaN,$1249,NaN
29,(Riverside Drive),NaN,$999,NaN
...,...,...,...,...
676,(4960 EDMONDSON PIKE),NaN,$979,NaN
677,(Smyrna),NaN,$1225,NaN
678,(4960 Edmondson Pike),NaN,$979,NaN
679,(Antioch),NaN,$790,NaN
680,"(1430 Bell Road, Nashville, TN 37211)",NaN,$1097,NaN
681,(The Gulch),NaN,$2499,NaN
682,(Brentwood),NaN,$1314,NaN
683,(laVergne),NaN,$1200,NaN
684,(Nashville),NaN,$1060,NaN
685,(Nashville),NaN,$1060,NaN
686,(Antioch),NaN,$790,NaN
687,(Downtown Nashville),(844) 538-9754,$1500,1 Bed
688,"(SoBro, The Gulch)",(844) 310-5291,$2100,3 Beds
689,(Historic Edgefield),(844) 891-6174,$2250,2 Beds
690,(Bellmont-Hillsboro),(844) 614-0437,$1500,1 Bed
691,(Cumberland Gardens),(844) 887-7125,$850,2 Beds
692,(Bellmont-Hillsboro),(844) 310-5055,$1800,2 Beds
693,(East End),(877) 432-6013,$1500,2 Beds
694,(West End Park),(844) 310-5300,$1350,1 Bed
695,(West End Park),(844) 629-2927,$2900,3 Beds
696,"(8th Ave South, Breeze Hill)",(844) 330-0704,$2800,3 Beds
697,(Green Hills),(844) 397-0032,$2295,3 Beds
698,(Green Hills),(888) 923-3149,$1100,1 Bed
699,(Green Hills),(844) 508-2643,$4650,4 Beds
700,(Green Hills),(877) 503-2074,$3199,5 Beds
701,(Miro Meadows),(844) 876-5926,$1200,2 Beds
702,(Charlotte Park),(844) 892-0517,$1100,2 Beds
703,(Hargis Heights),(844) 289-7726,$1500,3 Beds
704,(Bellshire Terrace),(844) 434-3089,$1475,3 Beds
705,(Marrowbone),(844) 778-3198,$1695,3 Beds